from __future__ import annotations
from typing import Dict, List

from app.domain.player import Player


def load_rosters_by_team_name() -> Dict[str, List[Player]]:
    """Rosters keyed by *team name* exactly as used in teams.py."""
    return {
        "CSM CSU Oradea": [
            Player("oradea_01", "Ionut Berceanu", "C", 203),
            Player("oradea_02", "Thomas Bropleh", "SG", 195),
            Player("oradea_03", "Nikola Kocovic", "SF", 197),
            Player("oradea_04", "Jaizec Lottie", "PG", 184),
            Player("oradea_05", "Luca Nastrut", "SF", 193),
            Player("oradea_06", "Bobe Nicolescu", "SF", 199),
            Player("oradea_07", "Emmanuel Nzekwesi", "PF", 203),
            Player("oradea_08", "Sayeed Pridgett", "SG", 197),
            Player("oradea_09", "Kristopher Richard", "SF", 196),
            Player("oradea_10", "Marian Schmidt", "C", 206),
            Player("oradea_11", "Bandja Sy", "PF", 203),
            Player("oradea_12", "Rolland Torok", "C", 202),
            Player("oradea_13", "Kalif Young", "C", 206),
        ],

        "CSO Voluntari": [
            Player("voluntari_01", "Sacar Anim", "SG", 197),
            Player("voluntari_02", "Solomon Young", "C", 201),
            Player("voluntari_03", "Kodi Justice", "SG", 199),
            Player("voluntari_04", "Lee Skinner", "SF", 198),
            Player("voluntari_05", "Mike Caffey", "PG", 182),
            Player("voluntari_06", "Giordan Watson", "PG/SG", 177),
            Player("voluntari_07", "Mouhamed Barro", "C", 204),
            Player("voluntari_08", "Laszlo Polyak", "PG", 190),
            Player("voluntari_09", "Alexandru Olah", "C", 213),
            Player("voluntari_10", "Tudor Girbea", "PF", 197),
            Player("voluntari_11", "David Patru", "PG", 186),
        ],

        "Dinamo Bucuresti": [
            Player("dinamo_01", "Derrick Marks", "SG", 189),
            Player("dinamo_02", "Marcus Lewis", "SG", 194),
            Player("dinamo_03", "Vyacheslav Bobrov", "PF", 203),
            Player("dinamo_04", "Nandor Kuti", "SG", 196),
            Player("dinamo_05", "Radu Virna", "SG", 190),
            Player("dinamo_06", "Ousmane Drame", "C", 206),
            Player("dinamo_07", "Stefan Grasu", "PF", 200),
            Player("dinamo_08", "Robin Mandisodza", "SG", 180),
            Player("dinamo_09", "Mario Lazar", "PF", 200),
            Player("dinamo_10", "Serban Jeles", "PF", 196),
        ],

        "FC Arges Pitesti": [
            Player("arges_01", "Marcus Thornton", "PG", 193),
            Player("arges_02", "Kendall Lewis", "SF", 200),
            Player("arges_03", "Catalin Baciu", "C", 214),
            Player("arges_04", "Elijah Joiner", "PG", 190),
            Player("arges_05", "Radovan Dokovic", "SG", 196),
            Player("arges_06", "Zach Smith", "PF", 203),
            Player("arges_07", "Nicolas Vanel", "SG", 182),
            Player("arges_08", "Teafale Lenard", "PG", 200),
            Player("arges_09", "Tudor Somacescu", "PG", 188),
            Player("arges_10", "Matei Dorneanu", "SF", 196),
            Player("arges_11", "Andrei Oinaru", "C", 200),
            Player("arges_12", "Marius Ciotlaus", "SF", 194),
        ],

        "SCM Politehnica Timisoara": [
            Player("timisoara_01", "Bogic Vujosevic", "PG", 192),
            Player("timisoara_02", "Devon Thomas", "PG", 183),
            Player("timisoara_03", "Adam Mirkovic", "SG/SF", 199),
            Player("timisoara_04", "Jalen Nesbitt", "SG", 178),
            Player("timisoara_05", "Sasa Borovnjak", "PF/C", 206),
            Player("timisoara_06", "Robert Schipor", "PG", 190),
            Player("timisoara_07", "George Blaj-Voinescu", "PF", 200),
            Player("timisoara_08", "Mirel Dragoste", "PG", 184),
            Player("timisoara_09", "Dejan Bjelic", "C", 209),
            Player("timisoara_10", "Marcu Badiu", "PG", 192),
            Player("timisoara_11", "Laszlo Lazar", "PF/C", 210),
        ],

        "CSM Corona Brasov": [
            Player("brasov_01", "Selim Fofana", "PG", 190),
            Player("brasov_02", "Tyrell Johnson", "PF", 204),
            Player("brasov_03", "Munis Tutu", "SG", 185),
            Player("brasov_04", "Mihai Maciuca", "SF", 195),
            Player("brasov_05", "Dimitrije Nikolic", "C", 211),
            Player("brasov_06", "Grant Shepard", "C", 210),
            Player("brasov_07", "Isiah Osborne", "SG", 196),
            Player("brasov_08", "David Antonescu", "SF/PF", 195),
            Player("brasov_09", "Andrei Petica", "SF", 192),
            Player("brasov_10", "David Lapuste", "PG", 185),
        ],

        "SCMU Craiova": [
            Player("craiova_01", "Sam Sessoms", "PG", 182),
            Player("craiova_02", "Ishmael Leggett", "SG", 187),
            Player("craiova_03", "Kendall Tyrek Robinson", "SG/SF", 198),
            Player("craiova_04", "Vlad Nistor", "PG/SG", 180),
            Player("craiova_05", "Tomas Zdanavicius", "C", 204),
            Player("craiova_06", "DeAndre Dishman", "SF", 198),
            Player("craiova_07", "David Vida", "SF", 197),
            Player("craiova_08", "Bogdan Tibirna", "C", 210),
            Player("craiova_09", "Serban Paul Puscasu", "PF", 203),
        ],

        "CSU Sibiu": [
            Player("sibiu_01", "M.J. Randolph", "PG", 192),
            Player("sibiu_02", "Anthony Smith", "PF", 201),
            Player("sibiu_03", "Keith Stone", "SF", 202),
            Player("sibiu_04", "Tavon King", "PG", 179),
            Player("sibiu_05", "Andreas Blidaru", "PG/SG", 183),
            Player("sibiu_06", "Monyea Pratt", "SG", 196),
            Player("sibiu_07", "Eduard Roschnafsky", "C", 209),
            Player("sibiu_08", "Kai Edwards", "SF", 205),
            Player("sibiu_09", "Filip Adamovic", "PG", 181),
            Player("sibiu_10", "David Fintina", "SF", 195),
            Player("sibiu_11", "Paul Itu", "SG", 187),
        ],

        "Rapid Bucuresti": [
            Player("rapid_01", "Nikola Jevtovic", "PF/C", 208),
            Player("rapid_02", "Roman Penn", "PG", 179),
            Player("rapid_03", "Lewis Sullivan", "SF", 201),
            Player("rapid_04", "Trendon Hankerson", "PG", 187),
            Player("rapid_05", "Aurelian Gavriloaia", "SF", 196),
            Player("rapid_06", "Oleksandr Lypovyy", "SG", 200),
            Player("rapid_07", "Tudor Gheorghe", "PG", 184),
            Player("rapid_08", "Tudor Fometescu", "SG", 192),
            Player("rapid_09", "Nikola Markovic", "C", 210),
            Player("rapid_10", "Edward Petrescu", "PF", 200),
            Player("rapid_11", "Andrei Cristian Muresan", "C", 198),
        ],

        "CSM Targu Mures": [
            Player("tgmures_01", "Goran Martinic", "PG", 187),
            Player("tgmures_02", "Trey Diggs", "SF", 197),
            Player("tgmures_03", "Michaelyn Scott", "PG", 183),
            Player("tgmures_04", "Pavle Reljic", "SG", 194),
            Player("tgmures_05", "Szabolcs Santa", "C", 209),
            Player("tgmures_06", "Bogdan Popa", "C", 213),
            Player("tgmures_07", "Vlad Corpodean", "SF", 192),
            Player("tgmures_08", "Trey Sampson", "SF", 205),
            Player("tgmures_09", "Milija Mikovic", "PF/C", 205),
            Player("tgmures_10", "Ioan Borsa", "PF", 200),
        ],

        "CSA Steaua Sharks Bucuresti": [
            Player("steaua_01", "Demilade Adelekun", "SF", 202),
            Player("steaua_02", "Kenny Dye", "PG", 180),
            Player("steaua_03", "Juwan Gray", "SF", 202),
            Player("steaua_04", "Brandon McKissic", "PG", 190),
            Player("steaua_05", "Albert Mark Stan", "SF", 192),
            Player("steaua_06", "Lorenzo Diaconescu", "PF", 202),
            Player("steaua_07", "George-Alexandru Vlad", "PG", 182),
            Player("steaua_08", "Alin Andries", "SF", 198),
            Player("steaua_09", "Vladimir Sparlac", "C", 202),
            Player("steaua_10", "Serban Matea", "PG", 184),
        ],

        "CSM BBA Petrolul Ploiesti": [
            Player("petrolul_01", "Veljko Brkic", "C", 206),
            Player("petrolul_02", "Andre Jones", "PG", 188),
            Player("petrolul_03", "Kenny Cooper", "PG", 182),
            Player("petrolul_04", "Devante Brooks", "PF", 198),
            Player("petrolul_05", "Jase Febres", "SG", 196),
            Player("petrolul_06", "Andrei Calenic", "C", 209),
            Player("petrolul_07", "Cristian Cotoara", "PF", 207),
        ],

        "CSM Targu Jiu": [
            Player("tgjiu_01", "Collin Cooper", "PG", 187),
            Player("tgjiu_02", "Lewis Djonkam", "SF", 205),
            Player("tgjiu_03", "Stefan Gribinic", "SF", 194),
            Player("tgjiu_04", "Mihai Carcoana", "C", 210),
            Player("tgjiu_05", "Luca Carstea", "PF", 194),
            Player("tgjiu_06", "Modibo Diaby", "C", 200),
            Player("tgjiu_07", "Alexandru Berca", "PG", 185),
        ],

        "CSM Galati": [
            Player("galati_01", "Marcus Randolph", "PG", 196),
            Player("galati_02", "Martynas Arlauskas", "PF", 201),
            Player("galati_03", "Mihailo Jovicic", "PG", 190),
            Player("galati_04", "Dragos Axinte", "SF", 193),
            Player("galati_05", "Nate Johnson", "C", 205),
            Player("galati_06", "Nicolae Ciuca", "C", 202),
            Player("galati_07", "Robert Stan", "C", 203),
            Player("galati_08", "David Brailescu", "SG", 196),
        ],

        "CS Valcea 1924": [
            Player("valcea_01", "Manu Lecomte", "PG", 178),
            Player("valcea_02", "Deandre Pinckney", "PF", 202),
            Player("valcea_03", "Terrell Harris", "SG", 193),
            Player("valcea_04", "Peter Kiss", "SG", 195),
            Player("valcea_05", "Kenny Gabriel", "PF", 206),
            Player("valcea_06", "Lucas Tohatan", "PG", 187),
            Player("valcea_07", "Patrick McCaffery", "SF", 205),
            Player("valcea_08", "Rares Uta", "C", 211),
            Player("valcea_09", "Amedeo Casale", "SF", 194),
            Player("valcea_10", "Titus Nicoara", "SF/PF", 203),
        ],

        "U-BT Cluj-Napoca": [
            Player("cluj_01", "Mitchell Creek", "SF", 195),
            Player("cluj_02", "Daron Russell", "PG", 180),
            Player("cluj_03", "Dusan Miletic", "C", 212),
            Player("cluj_04", "Nighael Ceaser", "PF", 202),
            Player("cluj_05", "Karel Guzman", "SF", 195),
            Player("cluj_06", "Iverson Molinar", "SG", 190),
            Player("cluj_07", "Trey Woodbury", "SG", 192),
            Player("cluj_08", "Patrick Richard", "SF", 196),
            Player("cluj_09", "Saulius Kulvietis", "PF", 203),
            Player("cluj_10", "Jeffery Taylor", "SG/SF", 202),
            Player("cluj_11", "Ben Altit", "C", 208),
            Player("cluj_12", "Tudor Petric", "PG", 190),
        ],
    }
