FROM python:3.10-slim

WORKDIR /app

# deps for psycopg2
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY . /app

EXPOSE 8000

CMD uvicorn app.api.main:app --host 0.0.0.0 --port ${PORT:-8000}